### ISSUE TITLE
Ubridge vmware can crash OSX

### ISSUE THREAD

**Issue by noplay** [GNS3/ubridge#6]
https://twitter.com/candanbolukbas/status/687925568441069568

**Comment by candanbolukbas** [comment]
Let me know if you need log or something else. 
My system:
Mac OS X Yosemite 10.10.5
VMware Fusion Professional Version 7.0.0 (2103067)
GNS3 1.4 and GNS3 VM.

**Comment by noplay** [comment]
For reproducing it we just need to put a vm with a bridge adapter in the topology?

**Comment by candanbolukbas** [comment]
I've configured GNS to use vmnet2 - vmnet255. This might be important too.
Then I've used GNS a number of times but suddenly my MAC crashed and continue to crash when I connect to internet even if GNS is closed. Lastly I removed GNS and the problem is gone.
I think the problem GNS overrides VMnet config in a way that it causes to system get crashed.
I can reproduce the issue if you want some more details. Thans Julien.

**Comment by candanbolukbas** [comment]
Hi Julian,

I think I got the problem. When we allow GNS to use vmnet2 - vmnet100 for VMware VMs it says 

`No VMnet interface available between vmnet2 and vmnet100. Go to preferences VMware / Network / Configure to add more interfaces.`

If we allow to use vmnet2 - vmnet255 it creates 250+ vmnet interfaces

    sh-3.2# ifconfig 
    vmnet1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:01 inet 192.168.41.1 netmask 0xffffff00 broadcast 192.168.41.255
    vmnet2: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:02 inet 172.16.0.1 netmask 0xffffff00 broadcast 172.16.0.255
    ...
    vmnet9: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:09 inet 172.16.5.1 netmask 0xffffff00 broadcast 172.16.5.255
    vmnet10: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:0a inet 172.16.6.1 netmask 0xffffff00 broadcast 172.16.6.255
    ...
    vmnet219: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:db inet 172.16.216.1 netmask 0xffffff00 broadcast 172.16.216.255
    vmnet220: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500 ether 00:50:56:c0:00:dc 	inet 172.16.217.1 netmask 0xffffff00 broadcast 172.16.217.255

    sh-3.2# ./vmnet-cli --status
    DHCP service on vmnet1 is not running
    Hostonly virtual adapter on vmnet1 is disabled
    Hostonly virtual adapter on vmnet2 is disabled
    Hostonly virtual adapter on vmnet4 is disabled
    Hostonly virtual adapter on vmnet5 is disabled
    Hostonly virtual adapter on vmnet6 is disabled
    Hostonly virtual adapter on vmnet7 is disabled
    DHCP service on vmnet8 is not running
    NAT service on vmnet8 is not running
    Hostonly virtual adapter on vmnet8 is disabled
    Hostonly virtual adapter on vmnet9 is disabled
    Hostonly virtual adapter on vmnet10 is disabled
    Hostonly virtual adapter on vmnet11 is disabled
    ...
    Hostonly virtual adapter on vmnet251 is disabled
    Hostonly virtual adapter on vmnet252 is disabled
    Hostonly virtual adapter on vmnet253 is disabled
    Hostonly virtual adapter on vmnet254 is disabled
    Hostonly virtual adapter on vmnet255 is disabled

When I changed the state of my physical network interface, it triggers 255 interfaces to reconfigure. I can't get the screenshot but I saw `ifconfig` hangs with %100 cpu usage. It causes to OS to crash this many interfaces to handle while VMware running. I hope you can reproduce, because I've fixed my MacOS :)

By the way the workaround solution would be to remove vmnet9+ interfaces from `/Library/Preferences/VMware\ Fusion/networking` file.

**Comment by grossmj** [comment]
@noplay can you reproduce this?

**Comment by noplay** [comment]
My mac seem stable even with large number of adapter. 

Due to the fact it's crash even when GNS3 is closed I suspect:
* an issue in OSX with large number of ethernet adapters (could have been fixed by an OSX upgrade)
* an issue in VMware with large number of ethernet adapters (could have been fixed by a VMware upgrade I have 7.1)
* a program like little snitch that crash  with large number of ethernet adapters
